name: PR Cleanup

on:
  pull_request:
    types: [unlabeled, closed]

jobs:
  clean-up:
    if: |
      (github.event.action == 'unlabeled' && github.event.label.name == 'deploy') ||
      (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_WEB_IDENTITY_TOKEN_FILE: '/tmp/awscreds'
      AWS_DEFAULT_REGION: us-east-2
      AWS_REGION: us-east-2
    permissions:
      id-token: write
      contents: read
      deployments: write

    steps:
      - name: set STAGE variable in environment for next steps
        run: |
          echo "STAGE=${{ github.event.number }}-${{ github.ref_name }}" >> $GITHUB_ENV
          echo "STAGE2=${{ github.event.number }}-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure AWS
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
          export AWS_WEB_IDENTITY_TOKEN=$(cat $AWS_WEB_IDENTITY_TOKEN_FILE)
          AWS_CREDS=$(aws sts assume-role-with-web-identity \
            --role-arn $AWS_ROLE_ARN \
            --role-session-name CdkDeploy \
            --duration-seconds 900 \
            --web-identity-token $AWS_WEB_IDENTITY_TOKEN)

          export AWS_ACCESS_KEY_ID=$(echo $AWS_CREDS | jq -r '.Credentials.AccessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDS | jq -r '.Credentials.SecretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $AWS_CREDS | jq -r '.Credentials.SessionToken')

      - name: Destroy PR stack
        run: yarn destroy:ci

      - name: Delete the deployment and the corresponding environment
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.STAGE }}
          desc: Environment was pruned

      - name: Delete the deployment and the corresponding environment
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.STAGE2 }}
          desc: Environment was pruned
