name: PR Deploy

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  deploy-app:
    concurrency: deploy-pr-${{ github.head_ref }}
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'deploy') ||
      (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_WEB_IDENTITY_TOKEN_FILE: '/tmp/awscreds'
      AWS_DEFAULT_REGION: us-east-2
      AWS_REGION: us-east-2
    permissions:
      id-token: write
      contents: read
      deployments: write

    steps:
      - name: set STAGE variable in environment for next steps
        run: echo "STAGE=${{ github.event.number }}-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create a deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.STAGE }}
          ref: ${{ github.head_ref }}
          override: true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure AWS
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
          export AWS_WEB_IDENTITY_TOKEN=$(cat $AWS_WEB_IDENTITY_TOKEN_FILE)
          AWS_CREDS=$(aws sts assume-role-with-web-identity \
            --role-arn $AWS_ROLE_ARN \
            --role-session-name CdkDeploy \
            --duration-seconds 900 \
            --web-identity-token $AWS_WEB_IDENTITY_TOKEN)

          export AWS_ACCESS_KEY_ID=$(echo $AWS_CREDS | jq -r '.Credentials.AccessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDS | jq -r '.Credentials.SecretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $AWS_CREDS | jq -r '.Credentials.SessionToken')

      - name: Deploy PR
        run: yarn deploy:ci

      - name: Update the deployment status
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.STAGE }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.cdk_deploy.outputs.api_url }}
